import type {
  CurrentUser, Session, SearchUser, InboxItem,
  AppNotification, LenderStats,
} from "./types";

export const CURRENT_USER: CurrentUser = {
  name: "Nthabi Sekhobe",
  phone: "+266 5800 1234",
  email: "nthabi.s@email.co.ls",
  whatsapp: "+266 5800 1234",
  isVerified: true,
  memberSince: "February 2025",
  avgRating: 4.3,
  totalCompleted: 8,
};

export const CONSUMER_SESSIONS: Session[] = [
  {
    id: "BS-2026-041",
    lenderName: "Lineo's Store",
    borrowerName: "Nthabi Sekhobe",
    borrowerPhone: "+266 5800 1234",
    amount: 1200,
    dueDate: "2026-08-20",
    status: "ACTIVE",
    description: "Cash advance for travel to Bloemfontein.",
    transactionType: "Cash Loan",
    createdAt: "2026-08-05",
    daysRemaining: 2,
  },
  {
    id: "BS-2026-039",
    lenderName: "Molise Finance",
    borrowerName: "Nthabi Sekhobe",
    borrowerPhone: "+266 5800 1234",
    amount: 4500,
    dueDate: "2026-08-15",
    status: "OVERDUE",
    description: "Business capital for July restocking.",
    transactionType: "Cash Loan",
    createdAt: "2026-07-15",
    daysRemaining: -3,
  },
  {
    id: "BS-2026-028",
    lenderName: "Thabo's Hardware",
    borrowerName: "Nthabi Sekhobe",
    borrowerPhone: "+266 5800 1234",
    amount: 600,
    dueDate: "2026-07-20",
    status: "COMPLETED",
    description: "Building materials on credit for home renovation.",
    transactionType: "Goods on Credit",
    createdAt: "2026-06-20",
    review: {
      rating: 4,
      comment: "Good borrower, paid a few days ahead of schedule.",
      date: "2026-07-21",
      reviewerName: "Thabo's Hardware",
    },
  },
  {
    id: "BS-2026-015",
    lenderName: "Makena Credit",
    borrowerName: "Nthabi Sekhobe",
    borrowerPhone: "+266 5800 1234",
    amount: 3000,
    dueDate: "2026-06-15",
    status: "DISPUTED",
    description: "Personal cash loan — emergency.",
    transactionType: "Cash Loan",
    createdAt: "2026-05-01",
    dispute: {
      issue: "I paid this loan on 14 June via FNB EFT. Lender marked me defaulted incorrectly.",
      filedAt: "2026-07-02",
      plausibility: "HIGH",
    },
  },
  {
    id: "BS-2025-089",
    lenderName: "Teboho Suppliers",
    borrowerName: "Nthabi Sekhobe",
    borrowerPhone: "+266 5800 1234",
    amount: 2200,
    dueDate: "2025-11-30",
    status: "COMPLETED",
    description: "School uniform supply on credit.",
    transactionType: "Goods on Credit",
    createdAt: "2025-10-01",
    review: {
      rating: 5,
      comment: "Excellent. Paid two weeks early. Highly trustworthy.",
      date: "2025-12-02",
      reviewerName: "Teboho Suppliers",
    },
  },
  {
    id: "BS-2025-061",
    lenderName: "Mapitso Finance",
    borrowerName: "Nthabi Sekhobe",
    borrowerPhone: "+266 5800 1234",
    amount: 1800,
    dueDate: "2025-08-31",
    status: "LATE",
    description: "Mekhatlo monthly contribution.",
    transactionType: "Mekhatlo",
    createdAt: "2025-07-10",
  },
];

export const LENDER_ALL_SESSIONS: Session[] = [
  {
    id: "BS-2026-001",
    borrowerName: "Thabo Mokoena",
    borrowerPhone: "+266 5867 3421",
    amount: 5000,
    dueDate: "2026-09-15",
    status: "ACTIVE",
    description: "Cash loan for business stock purchase at Maseru trading hub.",
    transactionType: "Cash Loan",
    createdAt: "2026-08-01",
    daysRemaining: 29,
  },
  {
    id: "BS-2026-002",
    borrowerName: "Palesa Ntsane",
    borrowerPhone: "+266 5912 8834",
    amount: 2500,
    dueDate: "2026-08-10",
    status: "OVERDUE",
    description: "Grocery goods on credit — household essentials.",
    transactionType: "Goods on Credit",
    createdAt: "2026-07-10",
    daysRemaining: -8,
  },
  {
    id: "BS-2026-003",
    borrowerName: "Lerato Mofokeng",
    borrowerPhone: "+266 5523 7761",
    amount: 800,
    dueDate: "2026-08-30",
    status: "PENDING",
    description: "Service credit for vehicle repair.",
    transactionType: "Service on Credit",
    createdAt: "2026-08-14",
    daysRemaining: 13,
  },
  {
    id: "BS-2026-007",
    borrowerName: "Rethabile Khotle",
    borrowerPhone: "+266 5881 2231",
    amount: 3500,
    dueDate: "2026-07-31",
    status: "UNCONFIRMED",
    description: "Cash loan — medical expenses.",
    transactionType: "Cash Loan",
    createdAt: "2026-06-30",
    daysRemaining: -18,
  },
  {
    id: "BS-2025-089",
    borrowerName: "Thabiso Sekhobe",
    borrowerPhone: "+266 5661 2234",
    amount: 3200,
    dueDate: "2026-01-15",
    status: "COMPLETED",
    description: "Cash loan — school fees assistance.",
    transactionType: "Cash Loan",
    createdAt: "2025-12-01",
    review: {
      rating: 5,
      comment: "Paid on time. Very reliable borrower.",
      date: "2026-01-16",
    },
  },
  {
    id: "BS-2025-074",
    borrowerName: "Mpho Tlali",
    borrowerPhone: "+266 5801 9934",
    amount: 1500,
    dueDate: "2026-02-28",
    status: "LATE",
    description: "Mekhatlo group contribution.",
    transactionType: "Mekhatlo",
    createdAt: "2026-01-10",
  },
  {
    id: "BS-2025-055",
    borrowerName: "Kefiloe Ramoeletsi",
    borrowerPhone: "+266 5744 0012",
    amount: 7000,
    dueDate: "2025-10-31",
    status: "DEFAULTED",
    description: "Business expansion loan — failed to repay.",
    transactionType: "Cash Loan",
    createdAt: "2025-09-01",
  },
  {
    id: "BS-2025-040",
    borrowerName: "Ntsoaki Moshoeshoe",
    borrowerPhone: "+266 5699 3341",
    amount: 900,
    dueDate: "2025-09-20",
    status: "COMPLETED",
    description: "Deposit towards food stall equipment.",
    transactionType: "Deposit To",
    createdAt: "2025-08-20",
    review: {
      rating: 4,
      comment: "Paid within the week of due date.",
      date: "2025-09-22",
    },
  },
];

export const LENDER_STATS: LenderStats = {
  issuedTotal: 12,
  activeAmount: 11800,
  lateCount: 2,
  unconfirmedCount: 1,
  totalDistributed: 45800,
};

export const SEARCH_RESULTS: SearchUser[] = [
  {
    id: "u1",
    name: "Thabo Mokoena",
    phone: "+266 5867 3421",
    isVerified: true,
    avgRating: 4.2,
    totalSessions: 7,
    completedSessions: 5,
    defaultedSessions: 0,
    lateSessions: 1,
    memberSince: "Jan 2024",
    reviews: [
      { rating: 5, comment: "Very reliable. Paid ahead of schedule.", date: "2026-01-16", reviewerName: "Lineo's Store" },
      { rating: 4, comment: "Paid on time, good communicator.", date: "2025-09-10", reviewerName: "Teboho Suppliers" },
      { rating: 3, comment: "Paid but needed reminders.", date: "2025-05-02", reviewerName: "Molise Finance" },
    ],
    sessions: [
      {
        id: "BS-2026-001",
        borrowerName: "Thabo Mokoena",
        borrowerPhone: "+266 5867 3421",
        lenderName: "Current Lender",
        amount: 5000,
        dueDate: "2026-09-15",
        status: "ACTIVE",
        description: "Cash loan for business stock purchase.",
        transactionType: "Cash Loan",
        createdAt: "2026-08-01",
        daysRemaining: 29,
      },
      {
        id: "BS-2025-110",
        borrowerName: "Thabo Mokoena",
        borrowerPhone: "+266 5867 3421",
        lenderName: "Lineo's Store",
        amount: 3200,
        dueDate: "2026-01-15",
        status: "COMPLETED",
        description: "Cash loan — school fees assistance.",
        transactionType: "Cash Loan",
        createdAt: "2025-12-01",
        review: { rating: 5, comment: "Paid on time. Very reliable borrower.", date: "2026-01-16", reviewerName: "Lineo's Store" },
      },
      {
        id: "BS-2025-082",
        borrowerName: "Thabo Mokoena",
        borrowerPhone: "+266 5867 3421",
        lenderName: "Teboho Suppliers",
        amount: 1800,
        dueDate: "2025-09-05",
        status: "COMPLETED",
        description: "Goods on credit for household supplies.",
        transactionType: "Goods on Credit",
        createdAt: "2025-08-01",
        review: { rating: 4, comment: "Paid on time, good communicator.", date: "2025-09-10", reviewerName: "Teboho Suppliers" },
      },
      {
        id: "BS-2025-041",
        borrowerName: "Thabo Mokoena",
        borrowerPhone: "+266 5867 3421",
        lenderName: "Molise Finance",
        amount: 2500,
        dueDate: "2025-04-28",
        status: "LATE",
        description: "Cash loan — emergency medical.",
        transactionType: "Cash Loan",
        createdAt: "2025-03-28",
        review: { rating: 3, comment: "Paid but needed reminders.", date: "2025-05-02", reviewerName: "Molise Finance" },
      },
    ],
  },
  {
    id: "u2",
    name: "Palesa Ntsane",
    phone: "+266 5912 8834",
    isVerified: true,
    avgRating: 3.8,
    totalSessions: 3,
    completedSessions: 2,
    defaultedSessions: 0,
    lateSessions: 1,
    memberSince: "Mar 2024",
    reviews: [
      { rating: 4, comment: "Honest borrower, slight delay but paid.", date: "2025-11-20", reviewerName: "Makena Credit" },
    ],
    sessions: [
      {
        id: "BS-2026-002",
        borrowerName: "Palesa Ntsane",
        borrowerPhone: "+266 5912 8834",
        lenderName: "Current Lender",
        amount: 2500,
        dueDate: "2026-08-10",
        status: "OVERDUE",
        description: "Grocery goods on credit — household essentials.",
        transactionType: "Goods on Credit",
        createdAt: "2026-07-10",
        daysRemaining: -8,
      },
      {
        id: "BS-2025-098",
        borrowerName: "Palesa Ntsane",
        borrowerPhone: "+266 5912 8834",
        lenderName: "Makena Credit",
        amount: 1200,
        dueDate: "2025-11-15",
        status: "COMPLETED",
        description: "Service credit — dressmaking supplies.",
        transactionType: "Service on Credit",
        createdAt: "2025-10-15",
        review: { rating: 4, comment: "Honest borrower, slight delay but paid.", date: "2025-11-20", reviewerName: "Makena Credit" },
      },
      {
        id: "BS-2025-061",
        borrowerName: "Palesa Ntsane",
        borrowerPhone: "+266 5912 8834",
        lenderName: "Teboho Suppliers",
        amount: 900,
        dueDate: "2025-07-30",
        status: "DISPUTED",
        description: "Goods on credit — stationery for school.",
        transactionType: "Goods on Credit",
        createdAt: "2025-06-30",
        dispute: {
          issue: "Payment was made on 28 July via M-Pesa. Lender marked as defaulted in error.",
          filedAt: "2025-08-05",
          plausibility: "MEDIUM",
        },
      },
    ],
  },
  {
    id: "u3",
    name: "Retselisitsoe Mofokeng",
    phone: "+266 5734 0912",
    isVerified: false,
    avgRating: 0,
    totalSessions: 0,
    completedSessions: 0,
    defaultedSessions: 0,
    lateSessions: 0,
    memberSince: "Jul 2026",
    reviews: [],
    sessions: [],
  },
];

export const INBOX_ITEMS: InboxItem[] = [
  {
    id: "INB-001",
    type: "session_offer",
    from: "Lineo's Store",
    fromPhone: "+266 5234 9981",
    amount: 3500,
    dueDate: "2026-10-01",
    description: "Grocery goods on credit for September month-end stock.",
    transactionType: "Goods on Credit",
    createdAt: "2026-08-16",
    status: "pending",
  },
  {
    id: "INB-002",
    type: "profile_request",
    from: "Molise Finance",
    fromPhone: "+266 5098 4421",
    createdAt: "2026-08-15",
    status: "pending",
  },
  {
    id: "INB-003",
    type: "session_offer",
    from: "Nthabiseng M.",
    fromPhone: "+266 5741 0023",
    amount: 800,
    dueDate: "2026-09-05",
    description: "Service credit for tailoring work.",
    transactionType: "Service on Credit",
    createdAt: "2026-08-13",
    status: "accepted",
  },
];

export const NOTIFICATIONS: AppNotification[] = [
  {
    id: "n1",
    type: "upcoming_due",
    message: "Session BS-2026-041 is due in 2 days (M 1,200 — Lineo's Store)",
    time: "Just now",
    read: false,
  },
  {
    id: "n2",
    type: "session_offer",
    message: "Lineo's Store sent you a new session offer — M 3,500",
    time: "2 hours ago",
    read: false,
  },
  {
    id: "n3",
    type: "profile_request",
    message: "Molise Finance requested to view your credit profile",
    time: "Yesterday",
    read: false,
  },
  {
    id: "n4",
    type: "status_update",
    message: "Session BS-2026-028 has been marked Completed by Thabo's Hardware",
    time: "3 days ago",
    read: true,
  },
  {
    id: "n5",
    type: "review",
    message: "Thabo's Hardware left you a 4-star review",
    time: "3 days ago",
    read: true,
  },
];

export const ACTIVITY_FEED = [
  { id: "a1", icon: "due", message: "Session BS-2026-041 is due in 2 days", time: "Just now" },
  { id: "a2", icon: "offer", message: "Lineo's Store sent you a session offer — M 3,500", time: "2 hours ago" },
  { id: "a3", icon: "review", message: "Thabo's Hardware left you a 4-star review", time: "3 days ago" },
  { id: "a4", icon: "status", message: "Session BS-2026-028 marked Completed", time: "3 days ago" },
];

export const ADMIN_WHATSAPP = "26659000000";
export const ADMIN_WHATSAPP_DISPLAY = "+266 5900 0000";

export const MONTHLY_COLLECTIONS = [
  { month: "Mar", collected: 4200, disbursed: 8000 },
  { month: "Apr", collected: 6800, disbursed: 5500 },
  { month: "May", collected: 3500, disbursed: 6000 },
  { month: "Jun", collected: 8900, disbursed: 7200 },
  { month: "Jul", collected: 5200, disbursed: 4000 },
  { month: "Aug", collected: 11800, disbursed: 3500 },
];
